version: '3'
services:
    
    easyspa-elasticsearch:
        build: easyspa-elasticsearch/
        ports:
            - "9200:9200"
        # Uncomment this section to have elasticsearch data loaded from a volume
        volumes:
           - ./log-data:/usr/share/elasticsearch/data
    easyspa-logstash:
        build: easyspa-logstash/
        environment:
            - INPUT_TCP_PORT=5000
            - INPUT_UDP_PORT=5000
            - INPUT_HTTP_PORT=5001
            - ELASTICSEARCH_HOST=easyspa-elasticsearch
            - ELASTICSEARCH_PORT=9200
            - LOGSTASH_DEBUG=true
        ports:
            - "5000:5000"
            - "5001:5001"
            - "9600:9600"
        depends_on:
            - easyspa-elasticsearch
